**1. Cargar el dataset**

In [1]:
import pandas as pd

df = pd.read_csv('Electric_Vehicle_Population_Data.csv')
df.head

<bound method NDFrame.head of         VIN (1-10)     County              City State  Postal Code  \
0       1C4JJXP66P     Kitsap           Poulsbo    WA      98370.0
1       1G1FX6S08K  Snohomish      Lake Stevens    WA      98258.0
2       WBY1Z2C58F       King           Seattle    WA      98116.0
3       5YJ3E1EBXK       King           Seattle    WA      98178.0
4       5YJSA1V24F     Yakima             Selah    WA      98942.0
...            ...        ...               ...   ...          ...
223990  7SAYGDEE4R     Pierce          Puyallup    WA      98374.0
223991  WBY8P2C00M  Snohomish      Lake Stevens    WA      98258.0
223992  JN1AZ0CP3B     Pierce  University Place    WA      98466.0
223993  5YJ3E1EA2R     Pierce          Puyallup    WA      98374.0
223994  WBY8P8C57K       King       Woodinville    WA      98072.0

        Model Year       Make     Model  \
0             2023       JEEP  WRANGLER
1             2019  CHEVROLET   BOLT EV
2             2015        BMW        I3
3             2019      TESLA   MODEL 3
4             2015      TESLA   MODEL S
...            ...        ...       ...
223990        2024      TESLA   MODEL Y
223991        2021        BMW        I3
223992        2011     NISSAN      LEAF
223993        2024      TESLA   MODEL 3
223994        2019        BMW        I3

                         Electric Vehicle Type  \
0       Plug-in Hybrid Electric Vehicle (PHEV)
1               Battery Electric Vehicle (BEV)
2               Battery Electric Vehicle (BEV)
3               Battery Electric Vehicle (BEV)
4               Battery Electric Vehicle (BEV)
...                                        ...
223990          Battery Electric Vehicle (BEV)
223991          Battery Electric Vehicle (BEV)
223992          Battery Electric Vehicle (BEV)
223993          Battery Electric Vehicle (BEV)
223994  Plug-in Hybrid Electric Vehicle (PHEV)

        Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0                   Not eligible due to low battery range            21.0
1                 Clean Alternative Fuel Vehicle Eligible           238.0
2                 Clean Alternative Fuel Vehicle Eligible            81.0
3                 Clean Alternative Fuel Vehicle Eligible           220.0
4                 Clean Alternative Fuel Vehicle Eligible           208.0
...                                                   ...             ...
223990  Eligibility unknown as battery range has not b...             0.0
223991  Eligibility unknown as battery range has not b...             0.0
223992            Clean Alternative Fuel Vehicle Eligible            73.0
223993  Eligibility unknown as battery range has not b...             0.0
223994            Clean Alternative Fuel Vehicle Eligible           126.0

        Base MSRP  Legislative District  DOL Vehicle ID  \
0             0.0                  23.0       258127145
1             0.0                  44.0         4735426
2             0.0                  34.0       272697666
3             0.0                  37.0       477309682
4             0.0                  15.0       258112970
...           ...                   ...             ...
223990        0.0                   2.0       264662359
223991        0.0                  44.0       157728168
223992        0.0                  28.0       261733433
223993        0.0                  25.0       275283487
223994        0.0                  45.0       267288801

                   Vehicle Location  \
0       POINT (-122.64681 47.73689)
1       POINT (-122.06402 48.01497)
2       POINT (-122.41067 47.57894)
3       POINT (-122.23825 47.49461)
4       POINT (-120.53145 46.65405)
...                             ...
223990  POINT (-122.27575 47.13959)
223991  POINT (-122.06402 48.01497)
223992  POINT (-122.53756 47.23165)
223993  POINT (-122.27575 47.13959)
223994  POINT (-122.15545 47.75448)

                                         Electric Utility  2020 Census Tract
0                                  PUGET SOUND ENERGY INC       5.303509e+10
1                                  PUGET SOUND ENERGY INC       5.306105e+10
2            CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303301e+10
3            CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303301e+10
4                                              PACIFICORP       5.307700e+10
...                                                   ...                ...
223990      PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.305307e+10
223991                             PUGET SOUND ENERGY INC       5.306105e+10
223992  BONNEVILLE POWER ADMINISTRATION||CITY OF TACOM...       5.305307e+10
223993      PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.305307e+10
223994      PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.303303e+10

[223995 rows x 17 columns]>

**2. Explorar el dataset**

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223995 entries, 0 to 223994
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         223995 non-null  object
 1   County                                             223992 non-null  object
 2   City                                               223992 non-null  object
 3   State                                              223995 non-null  object
 4   Postal Code                                        223992 non-null  float64
 5   Model Year                                         223995 non-null  int64
 6   Make                                               223995 non-null  object
 7   Model                                              223995 non-null  object
 8   Electric Vehicle Type                              223995 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  223995 non-null  object
 10  Electric Range                                     223977 non-null  float64
 11  Base MSRP                                          223977 non-null  float64
 12  Legislative District                               223521 non-null  float64
 13  DOL Vehicle ID                                     223995 non-null  int64
 14  Vehicle Location                                   223985 non-null  object
 15  Electric Utility                                   223992 non-null  object
 16  2020 Census Tract                                  223992 non-null  float64
dtypes: float64(5), int64(2), object(10)
memory usage: 29.1+ MB

In [3]:
df.describe(include='all')

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
count,223995,223992,223992,223995,223992.000000,223995.000000,223995,223995,223995,223995,223977.000000,223977.000000,223521.000000,2.239950e+05,223985,223992,2.239920e+05
unique,13175,207,789,48,NaN,NaN,46,164,2,3,NaN,NaN,NaN,NaN,952,76,NaN
top,7SAYGDEE7P,King,Seattle,WA,NaN,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,NaN,NaN,NaN,POINT (-122.13158 47.67858),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),NaN
freq,1179,113169,35664,223521,NaN,NaN,96180,46583,177151,130442,NaN,NaN,NaN,NaN,5511,81177,NaN
mean,NaN,NaN,NaN,NaN,98176.491165,2021.264408,NaN,NaN,NaN,NaN,47.736187,829.894386,28.876361,2.329328e+08,NaN,NaN,5.297997e+10
std,NaN,NaN,NaN,NaN,2544.240509,2.989676,NaN,NaN,NaN,NaN,84.987140,7372.509049,14.911023,6.884329e+07,NaN,NaN,1.531491e+09
min,NaN,NaN,NaN,NaN,1731.000000,1999.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,4.385000e+03,NaN,NaN,1.001020e+09
25%,NaN,NaN,NaN,NaN,98052.000000,2020.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,17.000000,2.008002e+08,NaN,NaN,5.303301e+10
50%,NaN,NaN,NaN,NaN,98126.000000,2022.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,32.000000,2.482992e+08,NaN,NaN,5.303303e+10
75%,NaN,NaN,NaN,NaN,98374.000000,2023.000000,NaN,NaN,NaN,NaN,39.000000,0.000000,42.000000,2.673973e+08,NaN,NaN,5.305307e+10
max,NaN,NaN,NaN,NaN,99577.000000,2025.000000,NaN,NaN,NaN,NaN,337.000000,845000.000000,49.000000,4.792548e+08,NaN,NaN,5.602100e+10

In [4]:
# df.columns

for col in df.columns:
    print(col)

VIN (1-10)
County
City
State
Postal Code
Model Year
Make
Model
Electric Vehicle Type
Clean Alternative Fuel Vehicle (CAFV) Eligibility
Electric Range
Base MSRP
Legislative District
DOL Vehicle ID
Vehicle Location
Electric Utility
2020 Census Tract

**3. Limpiar el dataset**

In [5]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223995 entries, 0 to 223994
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   vin_(1-10)                                         223995 non-null  object
 1   county                                             223992 non-null  object
 2   city                                               223992 non-null  object
 3   state                                              223995 non-null  object
 4   postal_code                                        223992 non-null  float64
 5   model_year                                         223995 non-null  int64
 6   make                                               223995 non-null  object
 7   model                                              223995 non-null  object
 8   electric_vehicle_type                              223995 non-null  object
 9   clean_alternative_fuel_vehicle_(cafv)_eligibility  223995 non-null  object
 10  electric_range                                     223977 non-null  float64
 11  base_msrp                                          223977 non-null  float64
 12  legislative_district                               223521 non-null  float64
 13  dol_vehicle_id                                     223995 non-null  int64
 14  vehicle_location                                   223985 non-null  object
 15  electric_utility                                   223992 non-null  object
 16  2020_census_tract                                  223992 non-null  float64
dtypes: float64(5), int64(2), object(10)
memory usage: 29.1+ MB

In [ ]:
df.duplicated().sum()
df.drop_duplicates(inplace=True) # remove duplicates
df.duplicated().sum() # check again

np.int64(0)

In [10]:
df.isnull().sum() # check for null values

vin_(1-10)                                             0
county                                                 3
city                                                   3
state                                                  0
postal_code                                            3
model_year                                             0
make                                                   0
model                                                  0
electric_vehicle_type                                  0
clean_alternative_fuel_vehicle_(cafv)_eligibility      0
electric_range                                        18
base_msrp                                             18
legislative_district                                 474
dol_vehicle_id                                         0
vehicle_location                                      10
electric_utility                                       3
2020_census_tract                                      3
dtype: int64

In [12]:
#Eliminamos las filas con valores nulos
df.dropna(inplace=True)
df.isnull().sum() # check again

vin_(1-10)                                           0
county                                               0
city                                                 0
state                                                0
postal_code                                          0
model_year                                           0
make                                                 0
model                                                0
electric_vehicle_type                                0
clean_alternative_fuel_vehicle_(cafv)_eligibility    0
electric_range                                       0
base_msrp                                            0
legislative_district                                 0
dol_vehicle_id                                       0
vehicle_location                                     0
electric_utility                                     0
2020_census_tract                                    0
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 223496 entries, 0 to 223994
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   vin_(1-10)                                         223496 non-null  object
 1   county                                             223496 non-null  object
 2   city                                               223496 non-null  object
 3   state                                              223496 non-null  object
 4   postal_code                                        223496 non-null  float64
 5   model_year                                         223496 non-null  int64
 6   make                                               223496 non-null  object
 7   model                                              223496 non-null  object
 8   electric_vehicle_type                              223496 non-null  object
 9   clean_alternative_fuel_vehicle_(cafv)_eligibility  223496 non-null  object
 10  electric_range                                     223496 non-null  float64
 11  base_msrp                                          223496 non-null  float64
 12  legislative_district                               223496 non-null  float64
 13  dol_vehicle_id                                     223496 non-null  int64
 14  vehicle_location                                   223496 non-null  object
 15  electric_utility                                   223496 non-null  object
 16  2020_census_tract                                  223496 non-null  float64
dtypes: float64(5), int64(2), object(10)
memory usage: 30.7+ MB

In [14]:
#guardar el dataframe limpio
df.to_csv('Electric_Vehicle_Population_Data_clean.csv', index=False)

In [15]:
df['electric_vehicle_type'].value_counts()

electric_vehicle_type
Battery Electric Vehicle (BEV)            176814
Plug-in Hybrid Electric Vehicle (PHEV)     46682
Name: count, dtype: int64